name: GitHub CI
on:
  push:
  pull_request:
  release:
    types: released

jobs:
  build-dotnet-core:
    name: Build .Net Core
    runs-on: linux-latest

    strategy:
      matrix:
        configuration: [ Release ]
        runtime-identifier: [ 'win-x64', 'win-x86', 'linux-x64', 'osx-x64', 'osx-arm64' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Publish the application
        run: dotnet publish de4dot --configuration ${{ matrix.configuration }} -f net6.0 --runtime ${{ matrix.runtime-identifier }} --self-contained false -p:PublishSingleFile=true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: de4dot-net6.0-${{ matrix.runtime-identifier }}
          path: |
            ${{ matrix.configuration }}/net6.0/${{ matrix.runtime-identifier }}/publish/
            !${{ matrix.configuration }}/net6.0/${{ matrix.runtime-identifier }}/publish/*.pdb
